package my.webstore.service;

import lombok.RequiredArgsConstructor;
import my.webstore.model.Order;
import my.webstore.model.User;
import my.webstore.repo.OrdersRepo;
import my.webstore.http.request.order.OrderRequest;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class OrdersService {

    private final OrdersRepo repo;
    private final UserService userService;

    public List<Order> getOrdersByUserId(String email) {
        User user = userService.getAllUserData(email);
        return repo.findByUserId(user.getId());
    }

    public List<Order> getOrders() {
        return repo.findAll();
    }

    public void addOrder(String email, OrderRequest request) {
        Integer userId = userService.getUserId(email);
        // order id is generated by DB
        Order order = Order.builder()
                .userId(userId)
                .date(request.date())
                .status(request.status())
                .price(request.price())
                .build();
        repo.save(order);
    }
}
