spring.application.name=webstore
spring.datasource.url=jdbc:postgresql://localhost:5432/webstore
spring.datasource.username=postgres
spring.datasource.password=1234

# saving the database after turning off the server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

